qbcore-framework/qb-smallresources

- client/handsup.lua
- client/teleports.lua
- config.lua
Bindable command
Can walk while hands are up
Toggle hu with the keybind or use the command
No loops
Closes https://github.com/qbcore-framework/qb-smallresources/issues/54
Closes https://github.com/qbcore-framework/qb-smallresources/issues/43
> add handsup script/configurable teleporter text

- client/handsup.lua
Changed handsup adnimation to be in line with rob in the qb-policejob
> Changed handsup adnimation to be in line with rob

- server/main.lua
> local src = source

- client/handsup.lua
This export will make it so you cannot put your hands up while cuffed
> fixes being able to put hands up while cuffed

- client/cruise.lua
Fixed spelling error in the places that have a comment for KMH but are meant to be MPH
> Fixed spelling error

- server/consumables.lua
Removed lockpicks from qb-vehiclekeys and moved to qb-smallresources
> Added Lockpicks

- client/handsup.lua
Added DisableControlAction for melee and vehicle movement
> update handsup.lua with DisableControlAction

- client/density.lua
> Adjust intensity

- client/afk.lua
- client/ignore.lua
add missing parameter to permission update event so afk works properly
> add missing parameter to permission update

- .github/workflows/lint.yml
- client/afk.lua
- client/binoculars.lua
- client/carwash.lua
- client/consumables.lua
- client/cruise.lua
- client/editor.lua
- client/fireworks.lua
- client/ignore.lua
- client/noshuff.lua
- client/point.lua
- client/recoil.lua
- client/removeentities.lua
- client/seatbelt.lua
- client/tackle.lua
- client/teleports.lua
- client/vehicletext.lua
- client/weapdraw.lua
- fxmanifest.lua
- server/consumables.lua
- server/logs.lua
- server/main.lua
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)
- Does your code fit the style guidelines? [yes/no]
- Does your PR fit the contribution guidelines? [yes/no]
> Fix linting issues

- client/recoil.lua
Fix the linting issue I made
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [no] (Be honest)
> fix(client/recoil): linting issue

- server/consumables.lua
Fixes hud updating thirst and hunger
> fix(server/consumables): fix hud update

- client/recoil.lua
Fixes the error with recoil on a nil value, should also keep the linter quiet about it
> fix(client/recoil): linter made an issue

- client/seatbelt.lua
Fixes that you can trigger your seatbelt when the pause menu is open
closes #246 
> fix(client/seatbelt): key usage with pausemenu open

- client/weapdraw.lua
This is a fix for issue #258 , it fixes the weapon pullout animation for police holsters , if the player is wearing a holster , it will show holster animation or else normal pullout animation.
This pr fixes the issue #258
> Fixed pulling weapon animation

- client/consumables.lua
Have been running this on a server since July. Let's make this happen!
There is only one thing on the server that currently reduces stress and that's weed.
Let's add in something else ALCOHOL!
Been running this on the server since July. :)
> Alcohol Reduces Stress

- client/seatbelt.lua
I'm working on integration of custom HUD into qb-core and met the issue with reading seatbelt status. This pull request just adds one parameter into event trigger with current state of the seatbelt.
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [**yes**/no] (Be honest)
- Does your code fit the style guidelines? [**yes**/no]
- Does your PR fit the contribution guidelines? [**yes**/no]
> [ENHANCEMENT] Trigger seatbelt event with state parameter

- client/removeentities.lua
- config.lua
The loop is not needed i added a polyzone instead of the distance check the object doesnt spawn back in until you are far from the area anyways.
> Object Removal loop Removed

- client/cruise.lua
- fxmanifest.lua
Fix client/cruise.lua => line 43
Fix fxmanifest with recent edit of removeentities
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? yes
- Does your code fit the style guidelines? yes
- Does your PR fit the contribution guidelines? yes
> fix linting issues and update fxmanifest

- server/logs.lua
created a log location for qb-jobs
QB-Jobs has logging and I created a key for it.
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes
- Does your code fit the style guidelines? [yes
- Does your PR fit the contribution guidelines? [yes
> [enhancement] Created Log Key for QB-Jobs

- fxmanifest.lua
Bumps the version number since the last PR accidentally changed the version to a lower number then before.
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality?
> No
- Does your code fit the style guidelines?
> Yes
- Does your PR fit the contribution guidelines?
> Yes
> [FIX] Bump version

- config.lua
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)
- Does your code fit the style guidelines? [yes/no]
- Does your PR fit the contribution guidelines? [yes/no]
> [FIX] Add missing config option

- config.lua
Duplicate config option for hud components.
> Duplicate Config.

- config.lua
Fixes #322
Sets Discord presence to false and removes someone's application ID from the framework.
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest) no
- Does your code fit the style guidelines? [yes/no] yes
- Does your PR fit the contribution guidelines? [yes/no] yes
> Remove ID for ThatLot FiveM server

- config.lua
add comments for hand bones
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? no, no need, just comments
- Does your code fit the style guidelines? maybe?
- Does your PR fit the contribution guidelines? idk
> bone comments

- config.lua
I added the `voltic2` as a blacklisted vehicle because people can buy them in the dealership and it's a weaponized car.
> Add voltic2 to blacklist

- locales/en.lua
- locales/pt.lua
- server/afk.lua
> Fix AFK kick message

- client/afk.lua
- config.lua
This PR just adds an Config option to decide if players which are AFK in the character menu should be kicked or not.
https://github.com/qbcore-framework/qb-multicharacter/issues/207
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality?no
> no
- Does your code fit the style guidelines?
> yes
- Does your PR fit the contribution guidelines?
> yes
> Add config option for afk kick in char menu

- client/ignore.lua
- config.lua
This PR is to add an option to remove pistol whipping and its an enhancement to the resource… Its been tested by me and works perfectly.
It also fixes https://github.com/qbcore-framework/qb-smallresources/issues/315 this issue
> Config Option for Remove Pistol Whipping

- client/tackle.lua
> fix cuff check

- fxmanifest.lua
- locales/pt-br.lua
- locales/pt.lua
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest) yes
- Does your code fit the style guidelines? [yes/no] yes
- Does your PR fit the contribution guidelines? [yes/no] yes
> fix language load and add pt-br language

- client/handsup.lua
Hotfix to fix an issue with handsup
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality?
- Does your code fit the style guidelines?
- Does your PR fit the contribution guidelines?
> fix: handsup hotfix

- client/ignore.lua
- client/seatbelt.lua
This PR holds the following fixes:
- Issue with seatbelts
- #410
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality?
- Does your code fit the style guidelines?
- Does your PR fit the contribution guidelines?
> fix: hotfixs

- client/weapdraw.lua
Remove extra Config
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)
- Does your code fit the style guidelines? [yes/no]
- Does your PR fit the contribution guidelines? [yes/no]
> Remove extra Config

- client/consumables.lua
Fixed a small animation bug in UseJoint.
There's a smokeweed2 animation for female characters.
> Update consumables.lua - Animation Bug.

- client/consumables.lua
- config.lua
Joints now Receive stress with the Config.RelieveStress option in the config
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [**yes**/no] (Be honest)
- Does your code fit the style guidelines? [**yes**/no]
- Does your PR fit the contribution guidelines? [**yes**/no]
> Relieve Stress config option, joints relieve stress
